pluginManagement {
    repositories {
        // 国内镜像加速（gradle 插件 / central 依赖）
        maven {
            name = 'AliyunPublic'
            url = 'https://maven.aliyun.com/repository/public'
        }
        maven {
            name = 'AliyunGradlePlugin'
            url = 'https://maven.aliyun.com/repository/gradle-plugin'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}
