org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range
minecraft_version_range=[1.20.1,1.21)
# The NeoForge version must agree with the Minecraft version to get a valid artifact
forge_version=47.4.22
# The NeoForge version range
forge_version_range=[47,51)
# The loader version range
loader_version_range=[47,)

## Mod Properties

mod_id=charlie_zoom
mod_name=Charlie Zoom
mod_license=MIT
mod_version=1.0.0
mod_group_id=org.example1
mod_authors=Charlie Zoom
mod_description=\u4e00\u952e\u653e\u5927\u6a21\u7ec4\uff1a\u6309\u4f4f C \u952e\u653e\u5927\u89c6\u91ce\uff08FOV \u5e73\u6ed1\u8fc7\u6e21\uff09\uff0c\u6eda\u8f6e\u8c03\u6574\u7f29\u653e\u500d\u6570\uff0c\u7075\u654f\u5ea6\u6309\u6bd4\u4f8b\u964d\u4f4e\u3002
